version: '3'
services:
    node:
        image: node:10
        command: yarn start
        volumes:
            - ./:/var/www/app/
        working_dir: /var/www/app/
        ports:
            - 4000:4000
        depends_on:
            - database
        env_file:
            - .env

    database:
        image: mongo:4.0.3
